
var names = [
	"Altoona Mountain City",
	"St. Louis Cardinals",
	"Texas Rangers",
	"Houston Colt .45's",
	"Pittsburgh Burghers",
	"Boston Red Caps",
	"Louisville Grays",
	"Philadelphia Centennials",
	"Brooklyn Superbas",
	"Montreal Expos",
	"Cleveland Bronchos",
	"Milwaukee Grays",
	"Cincinnati Red Stockings",
	"Los Angeles Dodgers",
	"Detroit Wolverines",
	"Colorado Rockies",
	"Boston Red Stockings",
	"Brooklyn Ward's Wonders",
	"Baltimore Marylands",
	"Richmond Virginians",
	"Milwaukee Braves",
	"San Francisco Giants",
	"Seattle Mariners",
	"Chicago Chi-Feds",
	"New York Yankees",
	"Cleveland Blues",
	"Chicago Cubs",
	"Troy Trojans",
	"Boston Doves",
	"Fort Wayne Kekiongas",
	"Indianapolis Hoosiers",
	"Brooklyn Atlantics",
	"Detroit Tigers",
	"Baltimore Canaries",
	"Milwaukee Brewers",
	"Kansas City Royals",
	"Philadelphia Quakers",
	"Los Angeles Angels of Anaheim",
	"Cincinnati Kelly's Killers",
	"Chicago/Pittsburgh (Union League)",
	"Brooklyn Gladiators",
	"Rochester Broncos",
	"California Angels",
	"Cleveland Indians",
	"Brooklyn Grays",
	"New York Giants",
	"Miami Marlins",
	"Philadelphia Athletics",
	"Brooklyn Robins",
	"Chicago White Sox",
	"Buffalo Blues",
	"Baltimore Terrapins",
	"Philadelphia Phillies",
	"Kansas City Cowboys",
	"Chicago Whales",
	"New York Highlanders",
	"Baltimore Orioles",
	"Toronto Blue Jays",
	"Louisville Colonels",
	"Florida Marlins",
	"Kansas City Athletics",
	"Pittsburg Alleghenys",
	"Los Angeles Angels",
	"Washington Olympics",
	"Rockford Forest Citys",
	"Houston Astros",
	"Chicago Orphans",
	"Cleveland Infants",
	"Washington Nationals",
	"Boston Red Sox",
	"Columbus Solons",
	"Syracuse Stars",
	"San Diego Padres",
	"Buffalo Bisons",
	"Brooklyn Bridegrooms",
	"Boston Bees",
	"St. Louis Maroons",
	"Newark Pepper",
	"Cincinnati Outlaw Reds",
	"Minnesota Twins",
	"St. Louis Perfectos",
	"Buffalo Buffeds",
	"Boston Americans",
	"Philadelphia Whites",
	"Atlanta Braves",
	"New York Metropolitans",
	"Philadelphia Keystones",
	"Tampa Bay Devil Rays",
	"Brooklyn Eckfords",
	"New Haven Elm Citys",
	"Seattle Pilots",
	"Boston Rustlers",
	"Anaheim Angels",
	"Boston Beaneaters",
	"New York Mutuals",
	"Baltimore Monumentals",
	"Cleveland Naps",
	"Keokuk Westerns",
	"Cleveland Forest Citys",
	"Cincinnati Reds",
	"Providence Grays",
	"Louisville Eclipse",
	"Columbus Buckeyes",
	"Toledo Maumees",
	"Middletown Mansfields",
	"Worcester Ruby Legs",
	"Indianapolis Blues",
	"Washington Statesmen",
	"Brooklyn Dodgers",
	"New York Gothams",
	"St. Paul White Caps",
	"Toledo Blue Stockings",
	"Cleveland Spiders",
	"Pittsburgh Pirates",
	"Boston Braves",
	"Philadelphia Blue Jays",
	"Tampa Bay Rays",
	"Pittsburgh Rebels",
	"Washington Blue Legs",
	"St. Louis Browns",
	"Cincinnati Redlegs",
	"Kansas City Packers",
	"Chicago White Stockings",
	"Hartford Dark Blues",
	"St. Louis Red Stockings",
	"Chicago Pirates",
	"St. Louis Terriers",
	"Chicago Colts",
	"Troy Haymakers",
	"Arizona Diamondbacks",
	"New York Mets",
	"Elizabeth Resolutes",
	"Brooklyn Grooms",
	"Washington Senators",
	"Brooklyn Tip-Tops",
	"Boston Reds",
	"Wilmington Quicksteps",
	"Oakland Athletics",
	"St. Louis Brown Stockings",
]

names.sort()

document.addEventListener('DOMContentLoaded', function() {

    var sel1 = document.getElementById('team1-select')
    var sel2 = document.getElementById('team2-select')
    for (var i = 0; i < names.length; i+=1) {
        var option = document.createElement("option")
        option.text = names[i]
        sel1.add(option)
        option = document.createElement("option")
        option.text = names[i]
        sel2.add(option)
    }

    console.log('worked')
})